# Generated by Django 5.0.2 on 2024-02-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=40)),
                ('tm', models.DateTimeField(editable=False)),
                ('feedback', models.TextField(help_text='Your feedback is valuable to us.')),
            ],
        ),
    ]
